### ISSUE TITLE
Not working in cakephp 3+

### ISSUE THREAD

**Issue by AquilaeNox** [st3ph/cakephp-breadcrumb#3]
Hi,

I'm using your plugin under CakePHP 3.5 and I can't have more than the current page (action/template) breadcrumb to get rendered. I've read your code and I can't find why it should, what I mean is I didn't spot where breadcrumbs history is saved in between requests? I hope you can help me to use your plugin, thank you.

**Comment by st3ph** [comment]
I'm not using CakePHP anymore since a while so I'm not sure I can help you

Anyway, I guess you have to "push" the breacrumb elements yourself from the controller (for example), it's not automatic for better control about your display and SEO

Hope this can help

**Comment by obinoob** [comment]
Well, that's exactly what I'm doing. I'm pushing each breadcrumb in every controller, and display the crumbs array under default.ctp the fact is that crumbs array never gets more than the last crumb as it gets lost after request. Not sure what am I missing but to me it is pretty clear. Probably the best solution is about to save crumbs in session config, db or even within filesystem.

`public function add()
    {
        **$this->Breadcrumb->push([
            'title' => 'Registar Cliente',
            'url' => Router::url("/clients/add"),
        ]);**

        $client = $this->Clients->newEntity();
        $districts = TableRegistry::get('Districts')->find('list');
        $towns = [];

        if ($this->request->is('post')) {
            $data = $this->request->getData();
            //updating towns
            $towns = TableRegistry::get('Towns')
                ->find('list')
                ->where([
                    'district_id' => $data['district_id']
                ]);

            $client = $this->Clients->patchEntity($client, $data);

            if ($this->Clients->save($client)) {
                try {
                    $this->save('ClientLogs', [
                        'message' => 'editou o cliente ' . $client->name,
                        'user_id' => $this->Auth->user('id'),
                        'client_id' => $client->id
                    ]);
                } catch (Exception $e) {
                    $this->log($e->getMessage(), LogLevel::ERROR);
                }
                $this->Flash->success('Cliente registado com sucesso');
                return $this->redirect(['controller' => 'clients', 'action' => 'view', $client->id]);
            } else {
                $this->log($e->getMessage(), LogLevel::ERROR);
                $this->Flash->error(__(ViewMessages::$deletedError));
            }
        }

        $this->set(compact('client', 'districts', 'towns'));
        $this->set('_serialize', 'client');
    }`

thank you

**Comment by AquilaeNox** [comment]
Well, that's exactly what I'm doing. I'm pushing each breadcrumb in every controller, and displaying the crumbs array under default.ctp the fact is that crumbs array never gets more than the last crumb as it gets lost after request. Not sure what am I missing but to me it is pretty clear. Probably the best solution is about to save crumbs in session config, db or even within filesystem.

```
public function add()
{
        $this->Breadcrumb->push([
            'title' => 'Registar Cliente',
            'url' => Router::url("/clients/add"),
        ]);
        ....
}    
```

thank you

**Comment by st3ph** [comment]
The plugin don't " remerber" the crumbs of the last request, you have to set them all each time.
When I used it, I set in the beforeFilter (for example) the base crumb, and then in each action I add a more specific one

**Comment by obinoob** [comment]
As far as I know you can only have one beforeFilter method by controller and call an action at a time so at most per request you got two crumbs! Not sure how you made that magic but seriously you could share that nah?

Thank you again for your time.
